### ISSUE TITLE
Signer

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-crypto#7]
Signing with private key of validator is needed in a few places:
* Consensus: Sign new block
* Consensus: Sign consensus vote
* Relayer: Sign eth transaction for committing new block.

We would like to have only one place where we load private key, and that place should have the ability to sign arbitrary hash that it receives from other parts of code.
The proposed way is to have `tokio::sync::mpsc` for incoming requests that would contain `tokio::sync::oneshot` to return signature in that way there is no exposing of secret info.

**Comment by Voxelot** [comment]
Since the signer is more like a 'leaf' node in terms of a dependency graph, shouldn't the signer module just be injected as an `Arc<dyn Signer>` wherever needed? It seems like a basic request-response pattern doesn't need the indirection of channels and simple async methods should suffice.

**Comment by Voxelot** [comment]
closing as most of the remaining work still needs to be done in fuel-crypto
